################################################################################
## Releasing the hounds in your local environment.
##
## Setup:
## $ gem install rubocop
##
## Run:
## $ rubocop ./path/to/file ./or/path/to/directory -c ./.hound.yml
##
## Generation Notes:
##   This file was generated via the commitment:install generator. You are free
##   and expected to change this file.
################################################################################
AllCops:
  TargetRubyVersion: 2.0
  Include:
    - Rakefile
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'spec/**/*'
    - 'db/**/*'
    - 'script/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Rails:
  Enabled: true
  Exclude:
    - app/controllers/application_controller.rb

LineLength:
  Description: 'Limit lines to 150 characters.'
  Max: 150
  Enabled: true
  Exclude:
   - spec/services/fedora_object_harvester_spec.rb
   - app/services/fedora_object_harvester.rb
   - app/services/metrics_report.rb

Style/StringLiterals:
  Description: 'Checks if uses of quotes match the configured preference.'
  Enabled: false

PercentLiteralDelimiters:
  Description: 'Use `%`-literal delimiters consistently'
  Enabled: false

Metrics/ClassLength:
  Max: 160
  Exclude:
     - app/services/fedora_object_harvester.rb

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 10
  Exclude:
   - app/services/fedora_object_harvester.rb
   - app/services/metrics_report.rb

Metrics/LineLength:
  Description: 'Limit lines to 150 characters.'
  Max: 150
  Enabled: false

Metrics/AbcSize:
  Enabled: true
  Max: 20
  Exclude:
   - app/services/fedora_object_harvester.rb

Lint/ParenthesesAsGroupedExpression:
  Enabled: true
  Exclude:
   - spec/services/fedora_object_harvester_spec.rb

Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: true
  Exclude:
  - spec/**/*
  - test/**/*
