sudo: false
cache: bundler

language: ruby
rvm:
  - 2.3.1
  - 2.2.5
  - 2.1.10

matrix:
  allow_failures:
    - rvm: "2.3.1"

before_install: gem install bundler -v 1.12.5

script: 'bundle exec rake'
