sudo: false
cache: bundler

language: ruby
rvm:
  - 2.4.2
  - 2.3.5
  - 2.2.8
  - 2.1.10

matrix:
  allow_failures:
    - rvm: "2.3.5"
    - rvm: "2.4.2"

before_install: gem install bundler -v 1.12.5

script: 'bundle exec rake'
