staging: &STAGING
  database: metrics_staging
  username: metrics
  password: allthew0rld
  host:     localhost
  adapter:  mysql2
  encoding: utf8
  pool:     5
  timeout:  5000

staging_bendo_database:
  <<: *STAGING
  database: bendo_staging
  username: bendo
  password: bendoc1Adm1n
  host:     localhost
  adapter:  mysql2
  encoding: utf8
  pool:     5
  timeout:  5000
