development: &development
  smtp_host: smtp.gmail.com
  smtp_port: 587
  smtp_domain: gmail.com
  smtp_authentication_type: plain
  smtp_user_name: noreply@nd.edu
  smtp_password:
  smtp_enable_starttls_auto: true
  smtp_delivery_method: smtp
  tls: true

test: &test
  <<: *development
  smtp_delivery_method: smtp

deploy:
  <<: *test

ci:
  <<: *test

