name: metrics-ruby-ci

on:
  push:
jobs:
  test-metrics:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Install bundler
      run: gem install bundler -v 1.16.3
    - name: Install bundled dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rake

